app:
  name: "My Application"
  mode: "dev"
  port: 8081
  version: "1.0.0"
  description: "My Application"
  start_time: "2015-01-01 00:00:00"
  machine_id: 1

log:
  level: "debug"
  filename: "log/application.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "101.43.99.4"
  port: 3306
  username: "root"
  password: "123456"
  database: "go_web"
  max_connections: 10
  max_idle_connections: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_connections: 10
  max_idle_connections: 10






